import { BooksCategories } from "../models/booksCategories";
import { Book } from "../models/bookInterface";

export class VirtualDB{
    categories = [
        new BooksCategories('category a', []),
        new BooksCategories('category b', []),
        new BooksCategories('category c', []),
        new BooksCategories('category d', []),
    ]
    books!: Book[]
    constructor(){
        this.books = [
            new Book('Beautiful Disaster', 90,'Jamie McGuire','none', this.categories[0]),
            new Book('Fifty Shades of Grey', 88,'E.L. James','none', this.categories[1]),
            new Book('Hopeless', 70,' Colleen Hoover','none', this.categories[2]),
            new Book('The Fault in Our Stars', 50,' John Green','none', this.categories[3]),
            new Book('Divergent', 64,' Veronica Roth','none', this.categories[0]),
            new Book('Slammed', 88,'Colleen Hoover ','none', this.categories[1]),
            new Book('Effortless', 100,' S.C. Stephens','none', this.categories[2]),
            new Book('Easy', 86,'Tammara Webber','none', this.categories[3]),
            new Book('Bared to You', 72,' Sylvia Day','none', this.categories[0]),
            new Book('Thoughtless', 66,'S.C. Stephens','none', this.categories[1]),
            new Book('The Hunger Games', 68,'Suzanne Collins','none', this.categories[2]),
            new Book('Obsidian', 70,' Jennifer L. Armentrout','none', this.categories[3]),
            new Book('The Edge of Never', 98,'J.A. Redmerski ','none', this.categories[0]),
            new Book('Fallen Too Far', 94 ,' Abbi Glines','none', this.categories[1]),
            new Book('Walking Disaster', 88,'Jamie McGuire ','none', this.categories[2]),
            new Book('City of Bones', 76,'Cassandra Clare','none', this.categories[3]),
            new Book('Clockwork Angel', 102,'Cassandra Clare','none', this.categories[0]),
            new Book('On Dublin Street', 98 ,'Samantha Young','none', this.categories[1]),
            new Book('Pride and Prejudice', 68,'Jane Austen','none', this.categories[2]),
            new Book('Anna and the French Kiss', 72 ,'Stephanie Perkins','none', this.categories[3]),
            new Book('Hush, Hush', 60 ,'Becca Fitzpatrick','none', this.categories[0]),
            new Book('Vampire Academy', 88,'Richelle Mead','none', this.categories[1]),
            new Book('Wallbanger', 64,'Alice Clayton','none', this.categories[2]),
            new Book('Fifty Shades Freed', 74 ,'E.L. James','none', this.categories[3]),
            new Book('Gabriel`s Inferno', 58,'Sylvain Reynard','none', this.categories[0]),
            new Book('Reflected in You', 82,'Sylvia Day','none', this.categories[1]),
            new Book('Fifty Shades Darker', 48,'by E.L. James','none', this.categories[2]),
            new Book('Perfect Chemistry', 97,'Simone Elkeles','none', this.categories[3]),
            new Book('Twilight', 95,'Stephenie Meyer','none', this.categories[0]),
            new Book('The Coincidence of Callie & Kayden', 93,'Jessica Sorensen ','none', this.categories[1]),
            new Book('The Twilight Saga', 91,'Stephenie Meyer','none', this.categories[2]),
            new Book('The Boy Who Sneaks in My Bedroom Window', 89,'Kirsty Moseley ','none', this.categories[3]),
            new Book('Wait for You', 87,'J. Lynn','none', this.categories[0]),
            new Book('Point of Retreat', 85,'Colleen Hoover','none', this.categories[1]),
            new Book('The Host', 83,'Stephenie Meyer','none', this.categories[2]),
            new Book('Love Unscripted', 81,'Tina Reber','none', this.categories[3]),
            new Book('If I Stay', 79,' Gayle Forman','none', this.categories[0]),
            new Book('The Vincent Boys', 77,'Abbi Glines','none', this.categories[1]),
            new Book('Never Too Far', 75,'Abbi Glines','none', this.categories[2]),
            new Book('The Mighty Storm', 73,'Samantha Towle','none', this.categories[3]),
            new Book('Delirium', 71,'Lauren Oliver','none', this.categories[0]),
            new Book('The Sea of Tranquility', 69,'Katja Millay','none', this.categories[1]),
            new Book('Catching Fire', 67,'Suzanne Collins','none', this.categories[2]),
            new Book('The Secret of Ella and Micha', 65,'Jessica Sorensen','none', this.categories[3]),
            new Book('Rule', 63,'Jay Crownover','none', this.categories[0]),
            new Book('Reason to Breathe', 61,'Rebecca Donovan','none', this.categories[1]),
            new Book('Taking Chances', 59,'Molly McAdams','none', this.categories[2]),
            new Book('Onyx', 57,'Jennifer L. Armentrout','none', this.categories[3]),
            new Book('Down to You', 55,'M. Leighton','none', this.categories[0]),
            new Book('While It Lasts', 53,'Abbi Glines','none', this.categories[1]),
            new Book('Losing It', 51,'Cora Carmack','none', this.categories[2]),
            new Book('Shiver', 49,'Maggie Stiefvater','none', this.categories[3]),
            new Book('Halfway to the Grave', 47,'Jeaniene Frost','none', this.categories[0]),
            new Book('Rock Me', 48,'Cherrie Lynn','none', this.categories[1]),
            new Book('Fallen', 50,'Lauren Kate','none', this.categories[2]),
            new Book('Pushing the Limits', 52,'Katie McGarry','none', this.categories[3]),
            new Book('Playing for Keeps', 54,'R.L. Mathewson','none', this.categories[0]),
            new Book('Lover Awakened', 56,'J.R. Ward ','none', this.categories[1]),
            new Book('Opal', 58,'Jennifer L. Armentrout','none', this.categories[2]),
            new Book('Existence', 60,'Abbi Glines','none', this.categories[3]),
            new Book('Graceling', 62,'Kristin Cashore','none', this.categories[0]),
            new Book('Breathe', 64,'Abbi Glines','none', this.categories[1]),
            new Book('Bloodlines', 66,'Richelle Mead','none', this.categories[2]),
            new Book('Half-Blood', 68,'Jennifer L. Armentrout','none', this.categories[3]),
            new Book('Clash', 70,'Nicole Williams ','none', this.categories[0]),
            new Book('Gabriel`s Rapture', 72,'Sylvain Reynard ','none', this.categories[1]),
            new Book('Breaking Dawn', 74,'Stephenie Meyer','none', this.categories[2]),
            new Book('Real', 76,'Katy Evans','none', this.categories[3]),
            new Book('Where She Went', 78,'Gayle Forman ','none', this.categories[0]),
            new Book('Because of Low', 80,'Abbi Glines ','none', this.categories[1]),
            new Book('The Unbecoming of Mara Dyer', 82 ,'Michelle Hodkin','none', this.categories[2]),
            new Book('The Perfect Game', 84 ,'J. Sterling','none', this.categories[3]),
            new Book('This Man', 86 ,'Jodi Ellen Malpas','none', this.categories[0]),
            new Book('Lola and the Boy Next Door', 88 ,'Stephanie Perkins','none', this.categories[1]),
            new Book('Outlander', 90,'Diana Gabaldon','none', this.categories[2]),
            new Book('Rules of Attraction', 92 ,'Simone Elkeles','none', this.categories[3]),
            new Book('The Iron King', 94,'Julie Kagawa','none', this.categories[0]),
            new Book('My Favorite Mistake', 96,'Chelsea M. Cameron','none', this.categories[1]),
            new Book('Shatter Me', 98,'Tahereh Mafi','none', this.categories[2]),
            new Book('On the Island', 95,'Tracey Garvis Graves','none', this.categories[3]),
            new Book('Just for Now', 93,'Abbi Glines','none', this.categories[0]),
            new Book('The Vincent Brothers', 91,'','none', this.categories[1]),
            new Book('Naked', 89,'Raine Miller','none', this.categories[2]),
            new Book('Clockwork Prince', 87,' Cassandra Clare','none', this.categories[3]),
            new Book('Dark Lover', 85,'J.R. Ward','none', this.categories[0]),
            new Book('That Boy', 83,'Jillian Dodd','none', this.categories[1]),
            new Book('Love Unrehearsed', 81,'Tina Reber','none', this.categories[2]),
            new Book('Flat-Out Love', 79,'Jessica Park','none', this.categories[3]),
            new Book('The Truth About Forever', 77,'Sarah Dessen ','none', this.categories[0]),
            new Book('The Selection', 75,'Kiera Cass ','none', this.categories[1]),
            new Book('Crash', 73,'Nicole Williams ','none', this.categories[2]),
        ]
    }
}